//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D2P_GrasshopperTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D2P")]
        public string DefaultRootLayerName {
            get {
                return ((string)(this["DefaultRootLayerName"]));
            }
            set {
                this["DefaultRootLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 75, 58")]
        public global::System.Drawing.Color DefaultRootLayerColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultRootLayerColor"]));
            }
            set {
                this["DefaultRootLayerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D2P_COMPONENTS")]
        public string DefaultDimensionStyleName {
            get {
                return ((string)(this["DefaultDimensionStyleName"]));
            }
            set {
                this["DefaultDimensionStyleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":")]
        public char DefaultTypeDelimiter {
            get {
                return ((char)(this["DefaultTypeDelimiter"]));
            }
            set {
                this["DefaultTypeDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_")]
        public char DefaultLayerDelimiter {
            get {
                return ((char)(this["DefaultLayerDelimiter"]));
            }
            set {
                this["DefaultLayerDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public char DefaultNameDelimiter {
            get {
                return ((char)(this["DefaultNameDelimiter"]));
            }
            set {
                this["DefaultNameDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public char DefaultLayerDescriptionDelimiter {
            get {
                return ((char)(this["DefaultLayerDescriptionDelimiter"]));
            }
            set {
                this["DefaultLayerDescriptionDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public char DefaultJointDelimiter {
            get {
                return ((char)(this["DefaultJointDelimiter"]));
            }
            set {
                this["DefaultJointDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":")]
        public char DefaultLayerNameDelimiter {
            get {
                return ((char)(this["DefaultLayerNameDelimiter"]));
            }
            set {
                this["DefaultLayerNameDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#")]
        public char DefaultCountDelimiter {
            get {
                return ((char)(this["DefaultCountDelimiter"]));
            }
            set {
                this["DefaultCountDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$")]
        public char DefaultCloneDelimiter {
            get {
                return ((char)(this["DefaultCloneDelimiter"]));
            }
            set {
                this["DefaultCloneDelimiter"] = value;
            }
        }
    }
}
